Transforming DATA - apply() , map() , assign() , replace() ,rename(columns={old:new}) , sort_values() , sort_index() , reset_index() , rank() , Reorder Columns

In [85]:
import pandas as pd
df = pd.read_csv("raw_data.csv")

df2 = df.copy()
df2["tax"] = df2["income"].apply(lambda x : "20%" if x >= 60_000  else "10%")
print(df2)

    id          name   age country   gender   income  tax
0    1      John Doe  29.0     USA     Male  55000.0  10%
1    1      John Doe  29.0     USA     Male  55000.0  10%
2    2    Jane Smith   NaN  Canada   Female  62000.0  20%
3    3          Alex   NaN     USA  Unknown  47000.0  10%
4    4  Maria Garcia  34.0   Spain   Female      NaN  10%
5    5        Li Wei  27.0   China     Male  51000.0  10%
6    6           NaN  45.0   India   Female  73000.0  20%
7    7    Ahmed Khan  38.0     NaN     Male  68000.0  20%
8    8    Rachel Lee  29.0     USA   Female  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0  10%
10  10   Emily Davis  31.0     USA      NaN  58000.0  10%

In [86]:
gender_map = { "Male" : "M" , "Female" : "F","Unknown" : " - "}

df2["gender"] = df2["gender"].map(gender_map)
print(df2)

    id          name   age country gender   income  tax
0    1      John Doe  29.0     USA      M  55000.0  10%
1    1      John Doe  29.0     USA      M  55000.0  10%
2    2    Jane Smith   NaN  Canada      F  62000.0  20%
3    3          Alex   NaN     USA     -   47000.0  10%
4    4  Maria Garcia  34.0   Spain      F      NaN  10%
5    5        Li Wei  27.0   China      M  51000.0  10%
6    6           NaN  45.0   India      F  73000.0  20%
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%
8    8    Rachel Lee  29.0     USA      F  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%
10  10   Emily Davis  31.0     USA    NaN  58000.0  10%

In [87]:
df2 =  df2.assign( Incremented_Income = df2["income"]*1.1)
df2

    id          name   age country gender   income  tax  Incremented_Income
0    1      John Doe  29.0     USA      M  55000.0  10%             60500.0
1    1      John Doe  29.0     USA      M  55000.0  10%             60500.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%             68200.0
3    3          Alex   NaN     USA     -   47000.0  10%             51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%                 NaN
5    5        Li Wei  27.0   China      M  51000.0  10%             56100.0
6    6           NaN  45.0   India      F  73000.0  20%             80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%             74800.0
8    8    Rachel Lee  29.0     USA      F  62000.0  20%             68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%             49500.0
10  10   Emily Davis  31.0     USA    NaN  58000.0  10%             63800.0

In [88]:
df2["country"] = df2["country"].replace("USA","United States of America")
df2

,id,name,age,country,gender,income,tax,Incremented_Income
0,1,John Doe,29.0,United States of America,M,55000.0,10%,60500.0
1,1,John Doe,29.0,United States of America,M,55000.0,10%,60500.0
2,2,Jane Smith,NaN,Canada,F,62000.0,20%,68200.0
3,3,Alex,NaN,United States of America,-,47000.0,10%,51700.0
4,4,Maria Garcia,34.0,Spain,F,NaN,10%,NaN
5,5,Li Wei,27.0,China,M,51000.0,10%,56100.0
6,6,NaN,45.0,India,F,73000.0,20%,80300.0
7,7,Ahmed Khan,38.0,NaN,M,68000.0,20%,74800.0
8,8,Rachel Lee,29.0,United States of America,F,62000.0,20%,68200.0
9,9,Carlos Ruiz,NaN,Mexico,M,45000.0,10%,49500.0
10,10,Emily Davis,31.0,United States of America,NaN,58000.0,10%,63800.0

In [89]:
df2.columns = ["ID","NAME","AGE","COUNTRY","GENDER","INCOME","TAX","NEW INCOME"]
df2

,ID,NAME,AGE,COUNTRY,GENDER,INCOME,TAX,NEW INCOME
0,1,John Doe,29.0,United States of America,M,55000.0,10%,60500.0
1,1,John Doe,29.0,United States of America,M,55000.0,10%,60500.0
2,2,Jane Smith,NaN,Canada,F,62000.0,20%,68200.0
3,3,Alex,NaN,United States of America,-,47000.0,10%,51700.0
4,4,Maria Garcia,34.0,Spain,F,NaN,10%,NaN
5,5,Li Wei,27.0,China,M,51000.0,10%,56100.0
6,6,NaN,45.0,India,F,73000.0,20%,80300.0
7,7,Ahmed Khan,38.0,NaN,M,68000.0,20%,74800.0
8,8,Rachel Lee,29.0,United States of America,F,62000.0,20%,68200.0
9,9,Carlos Ruiz,NaN,Mexico,M,45000.0,10%,49500.0
10,10,Emily Davis,31.0,United States of America,NaN,58000.0,10%,63800.0

In [96]:
df2.rename(columns = {"INCOME":"SALARY"})
df2.rename(index = {1:"First"})

,ID,NAME,AGE,COUNTRY,GENDER,INCOME,TAX,NEW INCOME
0,1,John Doe,29.0,United States of America,M,55000.0,10%,60500.0
First,1,John Doe,29.0,United States of America,M,55000.0,10%,60500.0
2,2,Jane Smith,NaN,Canada,F,62000.0,20%,68200.0
3,3,Alex,NaN,United States of America,-,47000.0,10%,51700.0
4,4,Maria Garcia,34.0,Spain,F,NaN,10%,NaN
5,5,Li Wei,27.0,China,M,51000.0,10%,56100.0
6,6,NaN,45.0,India,F,73000.0,20%,80300.0
7,7,Ahmed Khan,38.0,NaN,M,68000.0,20%,74800.0
8,8,Rachel Lee,29.0,United States of America,F,62000.0,20%,68200.0
9,9,Carlos Ruiz,NaN,Mexico,M,45000.0,10%,49500.0
10,10,Emily Davis,31.0,United States of America,NaN,58000.0,10%,63800.0

In [113]:
df2.sort_values("INCOME")
df2.sort_values("INCOME" , ascending=False)
df2 = df2.fillna(100)
sorted_df = df2.sort_values(["INCOME" , "AGE"]) # age will be  2nd Parameter for Sorting
sorted_df.sort_index()

# reset
# sorted_df.reset_index()
sorted_df.reset_index(drop=True)

,ID,NAME,AGE,COUNTRY,GENDER,INCOME,TAX,NEW INCOME
0,4,Maria Garcia,34.0,Spain,F,100.0,10%,100.0
1,9,Carlos Ruiz,100.0,Mexico,M,45000.0,10%,49500.0
2,3,Alex,100.0,United States of America,-,47000.0,10%,51700.0
3,5,Li Wei,27.0,China,M,51000.0,10%,56100.0
4,1,John Doe,29.0,United States of America,M,55000.0,10%,60500.0
5,1,John Doe,29.0,United States of America,M,55000.0,10%,60500.0
6,10,Emily Davis,31.0,United States of America,100,58000.0,10%,63800.0
7,8,Rachel Lee,29.0,United States of America,F,62000.0,20%,68200.0
8,2,Jane Smith,100.0,Canada,F,62000.0,20%,68200.0
9,7,Ahmed Khan,38.0,100,M,68000.0,20%,74800.0
10,6,100,45.0,India,F,73000.0,20%,80300.0

In [128]:
sorted_df["Ranking"] = sorted_df["INCOME"].rank(ascending = True , method = "dense") # method -> min or max
sorted_df

,ID,NAME,AGE,COUNTRY,GENDER,INCOME,TAX,NEW INCOME,Ranking
4,4,Maria Garcia,34.0,Spain,F,100.0,10%,100.0,1.0
9,9,Carlos Ruiz,100.0,Mexico,M,45000.0,10%,49500.0,2.0
3,3,Alex,100.0,United States of America,-,47000.0,10%,51700.0,3.0
5,5,Li Wei,27.0,China,M,51000.0,10%,56100.0,4.0
0,1,John Doe,29.0,United States of America,M,55000.0,10%,60500.0,5.0
1,1,John Doe,29.0,United States of America,M,55000.0,10%,60500.0,5.0
10,10,Emily Davis,31.0,United States of America,100,58000.0,10%,63800.0,6.0
8,8,Rachel Lee,29.0,United States of America,F,62000.0,20%,68200.0,7.0
2,2,Jane Smith,100.0,Canada,F,62000.0,20%,68200.0,7.0
7,7,Ahmed Khan,38.0,100,M,68000.0,20%,74800.0,8.0
6,6,100,45.0,India,F,73000.0,20%,80300.0,9.0

In [129]:
sorted_df[["ID","Ranking","COUNTRY","GENDER","INCOME","TAX","NEW INCOME","NAME","AGE"]]

,ID,Ranking,COUNTRY,GENDER,INCOME,TAX,NEW INCOME,NAME,AGE
4,4,1.0,Spain,F,100.0,10%,100.0,Maria Garcia,34.0
9,9,2.0,Mexico,M,45000.0,10%,49500.0,Carlos Ruiz,100.0
3,3,3.0,United States of America,-,47000.0,10%,51700.0,Alex,100.0
5,5,4.0,China,M,51000.0,10%,56100.0,Li Wei,27.0
0,1,5.0,United States of America,M,55000.0,10%,60500.0,John Doe,29.0
1,1,5.0,United States of America,M,55000.0,10%,60500.0,John Doe,29.0
10,10,6.0,United States of America,100,58000.0,10%,63800.0,Emily Davis,31.0
8,8,7.0,United States of America,F,62000.0,20%,68200.0,Rachel Lee,29.0
2,2,7.0,Canada,F,62000.0,20%,68200.0,Jane Smith,100.0
7,7,8.0,100,M,68000.0,20%,74800.0,Ahmed Khan,38.0
6,6,9.0,India,F,73000.0,20%,80300.0,100,45.0