Melt and Pivot

In [4]:
# Melt 
import pandas as pd
df = pd.DataFrame({
    "country": ["USA", "USA", "India", "India"],
    "year": [2020, 2021, 2020, 2021],
    "sales": [100, 120, 90, 110],
    "profit": [20, 25, 18, 22],
    "tax":[10,20,30,20]
})

melted_df = df.melt(
    id_vars = ["country","year"],
    value_vars = ["sales" , "profit","tax"],
    var_name = "combined_column",
    value_name = "Value"
)
melted_df

   country  year combined_column  Value
0      USA  2020           sales    100
1      USA  2021           sales    120
2    India  2020           sales     90
3    India  2021           sales    110
4      USA  2020          profit     20
5      USA  2021          profit     25
6    India  2020          profit     18
7    India  2021          profit     22
8      USA  2020             tax     10
9      USA  2021             tax     20
10   India  2020             tax     30
11   India  2021             tax     20

In [7]:
#pivot
melted_df.pivot(
    index = ["country","year"], # paire - unique
    columns = "combined_column",
    values = "Value"
)

combined_column  profit  sales  tax
country year
India   2020         18     90   30
        2021         22    110   20
USA     2020         20    100   10
        2021         25    120   20